### ISSUE TITLE
Make monster affinities better

### ISSUE THREAD

**Issue by mbenfowler** [AllPurposeName/fabula-ultima-foundry-vtt#53]
![Image](https://github.com/AllPurposeName/fabula-ultima-foundry-vtt/assets/32660020/a2f56388-2386-4d46-b699-90833e484928)

I'm thinking that each field defaults to nothing (greyed-out), and each click on a box toggles through the 4 categories. Thoughts?

**Comment by siegfault** [comment]
So each field is a damage type, and clicking 4 times cycles through (some order of) resistant, vulnerable, immune, and nothing? Makes sense to me!
