### ISSUE TITLE
Clarify attribute fetches

### ISSUE THREAD

**Issue by siegfault** [AllPurposeName/fabula-ultima-foundry-vtt#7]
Currently, you can access attributes in two ways to get very different values:
* `this.actor.attributes.might.value`
* `this.actor.might`

The first is the base/raw value and the second is the modified/calculated version with status effects. We should rename one or both to remove ambiguity.

**Comment by AllPurposeName** [comment]
I think the only time we use base at all is for the calculation, so we could probably get away with the name change to `baseWillpower` and allow the callers to use `willpower` to their hearts content.
